# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json
name: Deploy
on:
  push:
    tags:        
      - 'v*'  
    branches:    
      - 'main'
    paths-ignore: # do not build for irrelvant changes like markdown files
      - '**.md'

jobs:
  build:
    runs-on: ubuntu-latest
    outputs:
      digest: ${{ steps.build-push.outputs.digest }}
    steps:
    - name: Login to GitHub Container Registry
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Generate docker metadata
      id: meta
      uses: docker/metadata-action@v4
      with:
        images: ghcr.io/wazbat/discord-minor-checker
    - name: Build and push
      id: build-push
      uses: docker/build-push-action@v3
      with:
        push: true
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}
